// Generated by tools/build_public_editions.py. Website copy; do not edit by hand.
window.DESKLEMUR_EDITION_GUIDE = {
  "schema_version": 1,
  "source": "build_release.py",
  "source_hash": "c6de240b01ab8d45b1cd33dc5f57e3da4dc7dec83d4c207edc4e5734905892c9",
  "editions": [
    {
      "id": "standard",
      "name": "Standard",
      "summary": "Local agents with bundled in-app llama.cpp.",
      "availability": "listed"
    },
    {
      "id": "pro",
      "name": "Pro",
      "summary": "Bundled local inference with DPMS for lower token usage and faster processing.",
      "availability": "listed"
    },
    {
      "id": "ultimate",
      "name": "Ultimate",
      "summary": "Additional model connections and individual agent models.",
      "availability": "closed"
    },
    {
      "id": "developer",
      "name": "Developer",
      "summary": "Model connection options and research tools.",
      "availability": "closed"
    }
  ],
  "rows": [
    {
      "id": "model_engine",
      "label": "Model engine",
      "description": "The model connection supported by each edition.",
      "values": {
        "standard": "Bundled in-app llama.cpp only",
        "pro": "Bundled in-app llama.cpp only",
        "ultimate": "Engine choice; llama.cpp in-app or server where available",
        "developer": "Engine choice; llama.cpp in-app or server where available"
      }
    },
    {
      "id": "engine_choice",
      "label": "Existing servers and web providers",
      "description": "Connect a compatible model server or supported web provider.",
      "values": {
        "standard": "Not available",
        "pro": "Not available",
        "ultimate": "Supported routes available",
        "developer": "Supported routes available"
      }
    },
    {
      "id": "agent_routes",
      "label": "Individual models for agents",
      "description": "Give an agent its own model connection.",
      "values": {
        "standard": "Shared workspace route",
        "pro": "Shared workspace route",
        "ultimate": "Available",
        "developer": "Available"
      }
    },
    {
      "id": "context_efficiency",
      "label": "Context usage comparison",
      "description": "Compare context usage for your setup.",
      "values": {
        "standard": "Included",
        "pro": "Included",
        "ultimate": "Included",
        "developer": "Included"
      }
    },
    {
      "id": "execution_state",
      "label": "DPMS",
      "description": "Reduces token usage to speed up processing.",
      "values": {
        "standard": "Not included",
        "pro": "Available",
        "ultimate": "Available",
        "developer": "Available"
      }
    },
    {
      "id": "research_memory",
      "label": "Experimental memory settings",
      "description": "Additional memory settings for research.",
      "values": {
        "standard": "Not included",
        "pro": "Not included",
        "ultimate": "Not included",
        "developer": "Research controls available"
      }
    },
    {
      "id": "direct_plasticity",
      "label": "Experimental learning controls",
      "description": "Research features that depend on the model and setup.",
      "values": {
        "standard": "Not included",
        "pro": "Not included",
        "ultimate": "Not included",
        "developer": "Research controls available"
      }
    },
    {
      "id": "public_api",
      "label": "App chat API",
      "description": "Connect other tools to the app's optional chat API.",
      "values": {
        "standard": "Normal chat API",
        "pro": "Normal chat API",
        "ultimate": "Normal chat API",
        "developer": "Normal chat and debug API"
      }
    },
    {
      "id": "diagnostics",
      "label": "Research diagnostics",
      "description": "Additional diagnostics and detailed runtime logs.",
      "values": {
        "standard": "Not included",
        "pro": "Not included",
        "ultimate": "Not included",
        "developer": "Research diagnostics; Detailed backend logs"
      }
    },
    {
      "id": "python_runtime",
      "label": "Python runtime",
      "description": "Use the bundled runtime or choose a runtime where supported.",
      "values": {
        "standard": "Bundled runtime only",
        "pro": "Bundled runtime only",
        "ultimate": "Bundled runtime only",
        "developer": "Runtime selection available"
      }
    }
  ],
  "notes": [
    {
      "title": "DPMS",
      "body": "Reduces token usage to speed up processing."
    },
    {
      "title": "Compatibility",
      "body": "Supported models and connections depend on the installed build, platform, and hardware. Ultimate and Developer are not publicly available."
    }
  ]
};
