// Generated by scripts/build_edition_guide.py from build_release.py. Do not edit.
window.DESKLEMUR_EDITION_GUIDE = {
  "schema_version": 1,
  "source": "build_release.py",
  "source_hash": "c6de240b01ab8d45b1cd33dc5f57e3da4dc7dec83d4c207edc4e5734905892c9",
  "editions": [
    {
      "id": "standard",
      "name": "Standard",
      "summary": "Local agents with bundled in-app llama.cpp.",
      "capabilities": {
        "agent_llm_config": false,
        "llm_engine_choice": false,
        "normal_chat_api": true,
        "context_efficiency": true,
        "execution_state_v1": false,
        "direct_plasticity": false,
        "full_dpms": false,
        "research_diagnostics": false,
        "debug_api": false,
        "verbose_runtime_logs": false
      }
    },
    {
      "id": "pro",
      "name": "Pro",
      "summary": "Local agents with bundled in-app llama.cpp; DPMS Execution State V1.",
      "capabilities": {
        "agent_llm_config": false,
        "llm_engine_choice": false,
        "normal_chat_api": true,
        "context_efficiency": true,
        "execution_state_v1": true,
        "direct_plasticity": false,
        "full_dpms": true,
        "research_diagnostics": false,
        "debug_api": false,
        "verbose_runtime_logs": false
      }
    },
    {
      "id": "ultimate",
      "name": "Ultimate",
      "summary": "Engine and provider choice; DPMS Execution State V1; individual model routes for agents.",
      "capabilities": {
        "agent_llm_config": true,
        "llm_engine_choice": true,
        "normal_chat_api": true,
        "context_efficiency": true,
        "execution_state_v1": true,
        "direct_plasticity": false,
        "full_dpms": true,
        "research_diagnostics": false,
        "debug_api": false,
        "verbose_runtime_logs": false
      }
    },
    {
      "id": "developer",
      "name": "Developer",
      "summary": "Engine and provider choice; DPMS Execution State V1; individual model routes for agents; experimental memory and research controls; Python runtime selection.",
      "capabilities": {
        "agent_llm_config": true,
        "llm_engine_choice": true,
        "normal_chat_api": true,
        "context_efficiency": true,
        "execution_state_v1": true,
        "direct_plasticity": true,
        "full_dpms": true,
        "research_diagnostics": true,
        "debug_api": true,
        "verbose_runtime_logs": true
      }
    }
  ],
  "rows": [
    {
      "id": "model_engine",
      "label": "Model engine",
      "description": "The inference route available to the workspace.",
      "values": {
        "standard": "Bundled in-app llama.cpp only",
        "pro": "Bundled in-app llama.cpp only",
        "ultimate": "Engine choice; llama.cpp in-app or server where available",
        "developer": "Engine choice; llama.cpp in-app or server where available"
      }
    },
    {
      "id": "engine_choice",
      "label": "Existing servers and web providers",
      "description": "Connect a compatible local or LAN model server, or configure a supported web provider.",
      "values": {
        "standard": "Not available",
        "pro": "Not available",
        "ultimate": "Supported routes available",
        "developer": "Supported routes available"
      }
    },
    {
      "id": "agent_routes",
      "label": "Individual model routes for agents",
      "description": "Assign an agent its own supported engine, endpoint, and model instead of the workspace route.",
      "values": {
        "standard": "Shared workspace route",
        "pro": "Shared workspace route",
        "ultimate": "Available",
        "developer": "Available"
      }
    },
    {
      "id": "context_efficiency",
      "label": "Context efficiency comparison",
      "description": "A read-only comparison of the current prompt and a local DPMS projection; it does not activate DPMS or prove a speedup.",
      "values": {
        "standard": "Included",
        "pro": "Included",
        "ultimate": "Included",
        "developer": "Included"
      }
    },
    {
      "id": "execution_state",
      "label": "DPMS Execution State V1",
      "description": "Carries bounded task state and tool evidence into planning instead of replaying raw tool history.",
      "values": {
        "standard": "Not included",
        "pro": "Available",
        "ultimate": "Available",
        "developer": "Available"
      }
    },
    {
      "id": "research_memory",
      "label": "Experimental memory controls",
      "description": "Research DPMS modes and diagnostic settings beyond the supported Execution State V1 profile.",
      "values": {
        "standard": "Not included",
        "pro": "Not included",
        "ultimate": "Not included",
        "developer": "Research controls available"
      }
    },
    {
      "id": "direct_plasticity",
      "label": "Direct Plasticity",
      "description": "Research controls that require a linked native lifecycle bridge and a supported, validated model profile.",
      "values": {
        "standard": "Not included",
        "pro": "Not included",
        "ultimate": "Not included",
        "developer": "Research controls available"
      }
    },
    {
      "id": "public_api",
      "label": "Public API",
      "description": "The optional public chat API is separate from the model-server connection and desktop controls.",
      "values": {
        "standard": "Normal chat API",
        "pro": "Normal chat API",
        "ultimate": "Normal chat API",
        "developer": "Normal chat and debug API"
      }
    },
    {
      "id": "diagnostics",
      "label": "Research diagnostics and backend logs",
      "description": "Additional research diagnostics and detailed backend runtime logs.",
      "values": {
        "standard": "Not included",
        "pro": "Not included",
        "ultimate": "Not included",
        "developer": "Research diagnostics; Detailed backend logs"
      }
    },
    {
      "id": "python_runtime",
      "label": "Python runtime",
      "description": "Whether the app uses only its bundled Python or permits runtime selection.",
      "values": {
        "standard": "Bundled runtime only",
        "pro": "Bundled runtime only",
        "ultimate": "Bundled runtime only",
        "developer": "Runtime selection available"
      }
    }
  ],
  "notes": [
    {
      "title": "Edition access and compatibility",
      "body": "Edition access does not guarantee model or engine compatibility. Available routes depend on the installed build, operating system, hardware, model, and required runtimes. In-app llama.cpp requires its library; a server-only package does not provide that transport."
    },
    {
      "title": "Execution State V1",
      "body": "Pro and Ultimate offer the supported Execution State V1 profile, keeping task state and tool evidence available during a run. Experimental memory controls are separate. Editions without Execution State V1 still include ordinary memory features."
    },
    {
      "title": "Local inference and network access",
      "body": "Standard and Pro run model inference inside the app without a model-server listener. Web research, downloads, connected tools, and the optional public chat API have separate network behavior."
    },
    {
      "title": "Individual routes and research features",
      "body": "An individual agent route needs an available endpoint and enough resources; selecting it does not automatically start another server. Research controls describe access, not guaranteed experimental results."
    }
  ]
};
